Add guide on error handling (+ Free Applicative)
xvw/preface pull request #116
Opened 2021-04-12 04:23 UTC by xvw

I try to give: 
- Sequential error handling using `Result/Try`
- Parallel error handling using `Validation/Validate`
- Canonical representation of Validation pipeline using a `Free Applicative` over `Validate`,

2021-04-12 09:23 UTC, gr-im requested changes
Hi, it is a very interesting guide. Thanks. Here is some small changement suggestion!

2021-04-12 09:23 UTC, gr-im commented on guides/error_handling.md
> +We could also perform a calculation that could fail... by dividing by
```diff
- We could also perform a calculation that could fail... by dividing by
+ We could also perform a computation that could fail... by dividing by
```

2021-04-12 09:23 UTC, gr-im commented on guides/error_handling.md
> +We could also perform a calculation that could fail... by dividing by
The change is on -calculation +computation

2021-04-12 09:23 UTC, gr-im commented on guides/error_handling.md
> +First, we need something to characterize a form:
`characterise`

2021-04-12 10:01 UTC, xvw commented on guides/error_handling.md
> + [Nickname_to_short "x"  Invalid_age (-23)  Invalid_email "abademail"]
Yes, it was a mstake (and now it is fixed for Nonempty_list and List ;) nice spot)

2021-04-12 10:01 UTC, xvw commented on guides/error_handling.md
> +`'a Validate.t list -> 'a list Validate,t` which seems to be exactly
EagleEye

2021-04-12 10:03 UTC, gr-im approved these changes
Thanks for the changes and the fixes.

2021-04-12 19:01 UTC, d-plaindoux requested changes

2021-04-13 09:20 UTC, xvw commented on guides/error_handling.md
> +- [Try](https://ocaml-preface.github.io/preface/Preface_stdlib/Try/index.html)
I put `Either` after the enumeration for more clarity, is that oké for you?

2021-04-13 09:20 UTC, xvw commented on guides/error_handling.md
> +  As `Result` is parameterized by two types, `Try` is a biased version
sure, it is done.

2021-04-13 09:20 UTC, xvw commented on guides/error_handling.md
> +errors on the fly. However, to ensure completeness of error handling,
done.

2021-04-13 09:21 UTC, xvw commented on guides/error_handling.md
> +But sometimes sequential validation can be an anti-pattern. For
I change it for dark-pattern. The sentence is explicit that can be "sometime" a dark pattern.

2021-04-13 11:58 UTC, d-plaindoux approved these changes

2021-04-13 12:01 UTC, merged